### ISSUE TITLE
[Feature]: Support undercurl highlighting

### ISSUE THREAD

**Issue by dromse** [uZer/pywal16.nvim#3]
Hi, it would be great to add undercurl highlighting for diagnostics. If you don't have time, I can add support for it and submit a PR.

**Comment by uZer** [comment]
Hi! Sorry for my late reply, I should definitely enable notifications...
Feel free to make a PR since I don't use undercurl yet, I'd gladly review it :)

**Comment by dromse** [comment]
@uZer I created a PR, check it out! 😃

**Comment by uZer** [comment]
Merged in https://github.com/uZer/pywal16.nvim/pull/4, thank you!
